<?php if(Mage::helper('inchoo_ticketmanager')->getCustomerCanReplyAll() || ($this->getTicket()->getData('customer_id') == Mage::getSingleton('customer/session')->getCustomer()->getId())):?>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-reply-validate">
    <?php if($this->getTicket()->hasData('ticket_id')): ?>
        <input type="hidden" id="ticket_id" name="ticket_id" value="<?php echo $this->getTicket()->getId()?>" />
    <?php endif; ?>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Add new Reply') ?></h2>
        <ul class="form-list">
            <li class="wide">
                <label for="ticket" class="required">Content:<em>*</em></label>
                <div class="input-box"><textarea id="reply" name="content" class="input-text required-entry" ></textarea></div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required">* Required Fields</p>
        <button type="submit" title="<?php echo $this->__('Post Reply') ?>" class="button"><span><span><?php echo $this->__('Post Reply') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    //< ![CDATA[
    var customForm = new VarienForm('form-reply-validate');
    //]]>
</script>
<?php endif?>