<div id="ticket_list_messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div>
	<h1><?php echo Mage::helper('inchoo_ticketmanager')->__("Tickets") ?></h1>
</div>

<div>
	<?php foreach ($this->getCollection() as $ticketItem): ?>
		<div id="item_<?php echo $ticketItem->getId() ?>">
			<h2>
				<a href="<?php echo $this->getItemUrl($ticketItem) ?>">
					<?php echo $this->escapeHtml($ticketItem->getSubject()) ?>
				</a>
			</h2>
		</div>
	<?php endforeach; ?>
</div>

<?php echo $this->getPager() ?>