<?php $_ticketItem = $this->helper('inchoo_ticketmanager')->getTicketItemInstance(); ?>
<div id="ticket_item_messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div>
	<h1><?php echo $this->escapeHtml($_ticketItem->getSubject()) ?></h1>
	<div>
		<div><?php echo $this->escapeHtml($_ticketItem->getMessage()) ?></div>
        <?php if(Mage::helper('inchoo_ticketmanager')->getEditTicketEnabled()): ?>
            <a href="<?php echo $this->getEditUrl() ?>">
                <?php echo Mage::helper('inchoo_ticketmanager')->__('Edit Ticket') ?>
            </a>
        <?php endif; ?>
        <div><?php echo $this->getChildHtml('reply.list'); ?></div>
        <div><?php echo $this->getChildHtml('reply.form'); ?></div>
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo Mage::helper('inchoo_ticketmanager')->__('Return to list') ?>
        </a>
	</div>
</div>