<div id="ticket_list_messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div>
	<h1><?php echo Mage::helper('inchoo_ticketmanager')->__("Tickets") ?></h1>
</div>
<div><a href="<?php echo Mage::getUrl("ticket/index/new") ?>">Add new Ticket</a></div>
<?php echo $this->getPagerHtml(); ?>
<div>
	<?php foreach ($this->getCollection() as $ticketItem): ?>
		<div id="item_<?php echo $ticketItem->getId() ?>">
			<h4>
				<a href="<?php echo $this->getItemUrl($ticketItem) ?>">
					<?php echo $this->escapeHtml($ticketItem->getSubject()) ?>
				</a>
                (<?php echo $ticketItem->getRepliesCount() ?>)-<?php echo Mage::helper('inchoo_ticketmanager')->__($ticketItem->getStatus())?>
			</h4>
		</div>
	<?php endforeach; ?>
</div>

<?php echo $this->getPager() ?>